In [2]:
import numpy as np

<h1> Task 1</h1>

In [3]:
# creating the 1 D numy array

arr = np.array([i for i in range(1,11)])
print(arr)
print(arr.size)
print(arr.shape)
print(arr.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
10
(10,)
int64


In [4]:
arr1 = np.arange(1,10).reshape(3,3)
print(arr1)
print(arr1.size)
print(arr1.shape)
print(arr1.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
(3, 3)
int64


In [5]:
arr2 = np.random.rand(3, 5, 3)
print(arr2)
print(arr2.size)
print(arr2.shape)
print(arr2.dtype)

[[[0.13900372 0.61981002 0.28698632]
  [0.04511773 0.99359393 0.84975961]
  [0.98492385 0.08605917 0.25528649]
  [0.90165484 0.85449008 0.57589053]
  [0.76410364 0.89582003 0.31042755]]

 [[0.4108117  0.25807912 0.26868197]
  [0.46686171 0.55640715 0.18319498]
  [0.54700423 0.63951155 0.18459466]
  [0.44760932 0.0311504  0.26174417]
  [0.95116145 0.65476076 0.1976794 ]]

 [[0.00335632 0.74129594 0.47594705]
  [0.42850203 0.74726928 0.0234801 ]
  [0.15273858 0.16804689 0.73720062]
  [0.94934823 0.5177479  0.20629897]
  [0.70746081 0.95490273 0.01074083]]]
45
(3, 5, 3)
float64


<h1> Task 2</h1>

In [6]:
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
arr = np.array(data)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [7]:
for i in range(3):
    print(arr[i])

10
20
30


In [ ]:
# Alternate element of an array

for i in range(0,arr.size,2):
    print(arr[i], end=" ")


10 30 50 70 90 

In [15]:
# reverse the array

arr1 = arr[::-1]
arr1

array([90, 80, 70, 60, 50, 40, 30, 20, 10])

<h1> Task 3 : Mathematical Operation </h1>

In [17]:
arr = np.random.rand(1,20)
arr

array([[0.31827107, 0.39128289, 0.87004917, 0.35541514, 0.28202586,
        0.79386902, 0.29070647, 0.69625214, 0.48500234, 0.30685273,
        0.29558284, 0.20048027, 0.28405156, 0.40003811, 0.89166326,
        0.20871939, 0.61985241, 0.01734939, 0.00206305, 0.43052061]])